import React, { useEffect, useState } from 'react';
import { keepPreviousData, useQuery } from '@tanstack/react-query';
import { Eye, Search } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import { platformApi } from '../../api/platformApi';
import PlatformLayout from '../../components/platform/PlatformLayout';
import { EmptyRow, ErrorPanel, StatusBadge } from '../../components/platform/PlatformUi';

const FeatureAccessPage=()=>{const navigate=useNavigate();const[page,setPage]=useState(0);const[input,setInput]=useState('');const[search,setSearch]=useState('');const[status,setStatus]=useState('');useEffect(()=>{const id=setTimeout(()=>{setSearch(input);setPage(0)},350);return()=>clearTimeout(id)},[input]);const filters={page,size:25,search,status};const q=useQuery({queryKey:['platform','feature-directory',filters],queryFn:()=>platformApi.featureDirectory(filters),placeholderData:keepPreviousData});return <PlatformLayout title="Feature Access" subtitle="Configured modules and effective runtime access"><div className="mb-5 grid gap-3 rounded-2xl border bg-white p-4 md:grid-cols-[1fr_220px]"><label className="flex items-center gap-2 rounded-xl border px-4"><Search size={16}/><input value={input} onChange={e=>setInput(e.target.value)} placeholder="Search institute or code" className="h-12 w-full outline-none"/></label><select value={status} onChange={e=>setStatus(e.target.value)} className="rounded-xl border px-4"><option value="">All subscription states</option>{['TRIAL','ACTIVE','PAST_DUE','EXPIRED'].map(x=><option key={x}>{x}</option>)}</select></div>{q.isError?<ErrorPanel error={q.error} retry={q.refetch}/>:<div className="overflow-hidden rounded-2xl border bg-white shadow-xl shadow-slate-200/30"><table className="w-full text-left"><thead className="bg-slate-950 text-[10px] uppercase tracking-widest text-white"><tr>{['Institute','Plan','Institute','Subscription','Configured','Effective',''].map(x=><th key={x} className="px-5 py-4">{x}</th>)}</tr></thead><tbody className="divide-y">{q.data?.content?.length?q.data.content.map(x=><tr key={x.instituteId}><td className="px-5 py-4"><strong>{x.instituteName}</strong><p className="text-xs text-slate-400">{x.institutionCode}</p></td><td className="px-5 py-4">{x.plan||'-'}</td><td className="px-5 py-4"><StatusBadge value={x.instituteStatus}/></td><td className="px-5 py-4"><StatusBadge value={x.subscriptionStatus||'Unassigned'}/></td><td className="px-5 py-4 font-bold">{x.configuredFeatures}</td><td className="px-5 py-4 font-bold">{x.effectiveFeatures}</td><td className="px-5 py-4"><button title="Manage features" onClick={()=>navigate(`/platform/institutes/${x.instituteId}?tab=Features`)} className="rounded-lg border p-2"><Eye size={16}/></button></td></tr>):<EmptyRow columns={7} text={q.isLoading?'Loading feature access...':'No institutes found'}/>}</tbody></table><div className="flex justify-end gap-3 border-t p-4"><button disabled={!page} onClick={()=>setPage(page-1)} className="rounded-lg border px-4 py-2 disabled:opacity-40">Previous</button><button disabled={page+1>=(q.data?.totalPages||0)} onClick={()=>setPage(page+1)} className="rounded-lg border px-4 py-2 disabled:opacity-40">Next</button></div></div>}</PlatformLayout>};
export default FeatureAccessPage;
