import InstituteSubscriptions from '../../components/platform/InstituteSubscriptions';
import React, { useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { ArrowLeft, Building2 } from 'lucide-react';
import { useNavigate, useParams, useSearchParams } from 'react-router-dom';
import { platformApi } from '../../api/platformApi';
import PlatformLayout from '../../components/platform/PlatformLayout';
import { ConfirmModal, ErrorPanel, PageSkeleton, StatusBadge, formatDate, formatMoney } from '../../components/platform/PlatformUi';

const tabs = ['Overview', 'Features', 'Subscription', 'Usage', 'Billing', 'Gateway', 'Activity', 'Internal Notes'];

const InstituteDetailsPage = () => {
  const { id } = useParams(); const instituteId = Number(id); const navigate = useNavigate(); const queryClient = useQueryClient(); const [params, setParams] = useSearchParams();
  const activeTab = params.get('tab') || 'Overview'; const [confirm, setConfirm] = useState(null); const [reason, setReason] = useState('');
  const detail = useQuery({ queryKey: ['platform', 'institute', instituteId], queryFn: () => platformApi.institute(instituteId) });
  const statusMutation = useMutation({ mutationFn: ({ action, payload }) => platformApi[action](instituteId, payload), onSuccess: () => { queryClient.invalidateQueries({ queryKey: ['platform', 'institute', instituteId] }); queryClient.invalidateQueries({ queryKey: ['platform', 'overview'] }); setConfirm(null); setReason(''); } });
  if (detail.isLoading) return <PlatformLayout title="Institute Details"><PageSkeleton /></PlatformLayout>;
  if (detail.isError || !detail.data) return <PlatformLayout title="Institute Details"><ErrorPanel error={detail.error} retry={detail.refetch} /></PlatformLayout>;
  const institute = detail.data;
  return <PlatformLayout title={institute.instituteName} subtitle={`${institute.institutionCode} | ${institute.type}`}>
    <button type="button" onClick={() => navigate('/platform/institutes')} className="mb-5 inline-flex items-center gap-2 text-xs font-black uppercase tracking-widest text-slate-500"><ArrowLeft size={16} />Back To Institutes</button>
    <div className="mb-6 flex flex-wrap items-center justify-between gap-4 rounded-2xl border border-slate-100 bg-white p-5 shadow-lg shadow-slate-200/20"><div className="flex items-center gap-4"><span className="rounded-xl bg-emerald-100 p-3 text-emerald-700"><Building2 size={24} /></span><div><p className="font-black text-slate-950">{institute.instituteName}</p><div className="mt-1 flex gap-2"><StatusBadge value={institute.status} /><StatusBadge value={institute.subscriptionStatus || 'Unassigned'} /></div></div></div><button type="button" onClick={() => { setReason(''); setConfirm(institute.status === 'SUSPENDED' ? 'reactivate' : 'suspend'); }} className={`rounded-xl px-5 py-3 text-xs font-black uppercase tracking-widest text-white ${institute.status === 'SUSPENDED' ? 'bg-emerald-600' : 'bg-rose-600'}`}>{institute.status === 'SUSPENDED' ? 'Reactivate' : 'Suspend'}</button></div>
    <div className="mb-6 overflow-x-auto border-b border-slate-200"><div className="flex min-w-max gap-1">{tabs.map((tab) => <button type="button" key={tab} onClick={() => setParams({ tab })} className={`border-b-2 px-4 py-3 text-xs font-black uppercase tracking-wider ${activeTab === tab ? 'border-emerald-600 text-emerald-700' : 'border-transparent text-slate-400'}`}>{tab}</button>)}</div></div>
    {activeTab === 'Overview' && <Overview data={institute} />}
    {activeTab === 'Features' && <Features instituteId={instituteId} />}
    {activeTab === 'Subscription' && <InstituteSubscriptions instituteId={instituteId} />}
    {activeTab === 'Usage' && <Usage instituteId={instituteId} />}
    {activeTab === 'Billing' && <Billing instituteId={instituteId} />}
    {activeTab === 'Gateway' && <Gateway instituteId={instituteId} />}
    {activeTab === 'Activity' && <Activity instituteId={instituteId} />}
    {activeTab === 'Internal Notes' && <Notes instituteId={instituteId} />}
    {confirm && <ConfirmModal title={confirm === 'suspend' ? 'Suspend Institute' : 'Reactivate Institute'} text={confirm === 'suspend' ? 'School access will be restricted. No school data will be deleted.' : 'School users will regain access under the active subscription.'} confirmLabel={confirm === 'suspend' ? 'Suspend' : 'Reactivate'} reason={reason} setReason={setReason} onClose={() => setConfirm(null)} busy={statusMutation.isPending} onConfirm={() => statusMutation.mutate({ action: confirm, payload: { reason, version: institute.version } })} />}
  </PlatformLayout>;
};

const Panel = ({ children }) => <div className="rounded-2xl border border-slate-100 bg-white p-6 shadow-lg shadow-slate-200/20">{children}</div>;
const Field = ({ label, value }) => <div><p className="text-[10px] font-black uppercase tracking-widest text-slate-400">{label}</p><p className="mt-2 text-sm font-bold text-slate-700">{value === null || value === undefined || value === '' ? 'Not set' : String(value)}</p></div>;
const Overview = ({ data }) => <div className="grid gap-6 xl:grid-cols-[1.4fr_1fr]"><Panel><h2 className="font-serif text-xl font-black italic">Registration Details</h2><div className="mt-6 grid gap-6 sm:grid-cols-2 lg:grid-cols-3"><Field label="Institution Code" value={data.institutionCode} /><Field label="Affiliation" value={data.affiliationNo} /><Field label="Affiliated From" value={data.affiliatedFrom} /><Field label="Email" value={data.email} /><Field label="Phone" value={data.contact} /><Field label="Location" value={`${data.city}, ${data.state}`} /><Field label="Registered" value={formatDate(data.registeredAt)} /><Field label="Plan" value={data.currentPlan} /><Field label="Subscription Expiry" value={formatDate(data.subscriptionExpiry)} /></div></Panel><Panel><h2 className="font-serif text-xl font-black italic">Institute Usage</h2><div className="mt-6 grid grid-cols-2 gap-4"><Field label="Students" value={data.studentCount} /><Field label="Teachers" value={data.teacherCount} /><Field label="Classes" value={data.classCount} /><Field label="Sections" value={data.sectionCount} /><Field label="Enabled Features" value={data.enabledFeatureCount} /><Field label="Gateway" value={data.gatewayStatus} /></div>{data.statusReason && <div className="mt-6 rounded-xl bg-rose-50 p-4 text-sm font-semibold text-rose-700">{data.statusReason}</div>}</Panel></div>;

const Features = ({ instituteId }) => {
  const client = useQueryClient(); const query = useQuery({ queryKey: ['platform', 'features', instituteId], queryFn: () => platformApi.features(instituteId) }); const [pending, setPending] = useState(null); const [reason, setReason] = useState('');
  const mutation = useMutation({ mutationFn: (payload) => platformApi.updateFeature(instituteId, payload), onSuccess: () => { client.invalidateQueries({ queryKey: ['platform', 'features', instituteId] }); client.invalidateQueries({ queryKey: ['platform', 'institute', instituteId] }); setPending(null); setReason(''); } });
  if (query.isLoading) return <PageSkeleton />; if (query.isError) return <ErrorPanel error={query.error} retry={query.refetch} />;
  return <><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{query.data.map((feature) => <Panel key={feature.code}><div className="flex items-start justify-between gap-3"><div><h3 className="font-black text-slate-900">{feature.label}</h3><p className="mt-1 text-xs font-semibold text-slate-400">{feature.source === 'PLAN' ? 'Plan default' : 'Manual override'}</p></div><button type="button" role="switch" aria-checked={feature.configuredEnabled} onClick={() => { setReason(''); setPending({ ...feature, enabled: !feature.configuredEnabled }); }} className={`relative h-7 w-12 rounded-full transition ${feature.configuredEnabled ? 'bg-emerald-600' : 'bg-slate-200'}`}><span className={`absolute top-1 h-5 w-5 rounded-full bg-white transition ${feature.configuredEnabled ? 'left-6' : 'left-1'}`} /></button></div><div className="mt-4 flex flex-wrap gap-2"><StatusBadge value={feature.configuredEnabled ? 'Configured' : 'Disabled'} /><StatusBadge value={feature.effectiveEnabled ? 'Effective' : feature.blockedReason || 'Blocked'} /></div></Panel>)}</div>{pending && <ConfirmModal title={`${pending.enabled ? 'Enable' : 'Disable'} ${pending.label}`} text="This changes configured access. Institute and subscription status still control effective access." confirmLabel={pending.enabled ? 'Enable' : 'Disable'} reason={reason} setReason={setReason} onClose={() => setPending(null)} busy={mutation.isPending} onConfirm={() => mutation.mutate({ featureCode: pending.code, enabled: pending.enabled, reason, version: pending.version })} />}</>;
};

const Usage = ({ instituteId }) => { const q=useQuery({queryKey:['platform','usage',instituteId],queryFn:()=>platformApi.usage(instituteId)}); if(q.isLoading)return <PageSkeleton/>;if(q.isError)return <ErrorPanel error={q.error} retry={q.refetch}/>;return <div className="grid grid-cols-2 gap-4 md:grid-cols-3 xl:grid-cols-5">{Object.entries(q.data).filter(([k])=>k!=='instituteId').map(([k,v])=><Panel key={k}><Field label={k.replace(/([A-Z])/g,' $1')} value={v}/></Panel>)}</div>; };
const Billing = ({ instituteId }) => { const q=useQuery({queryKey:['platform','billing',{instituteId}],queryFn:()=>platformApi.invoices({instituteId,page:0,size:25})});if(q.isLoading)return <PageSkeleton/>;if(q.isError)return <ErrorPanel error={q.error} retry={q.refetch}/>;return <Panel><h2 className="font-serif text-xl font-black italic">Platform Invoices</h2><div className="mt-5 space-y-3">{q.data.content.length?q.data.content.map(x=><div key={x.id} className="flex flex-wrap items-center justify-between gap-3 rounded-xl border border-slate-100 p-4"><div><p className="font-black">{x.invoiceNumber}</p><p className="text-xs text-slate-400">Due {formatDate(x.dueDate)}</p></div><div className="flex items-center gap-3"><strong>{formatMoney(x.totalAmount)}</strong><StatusBadge value={x.status}/></div></div>):<p className="py-8 text-center text-slate-400">No platform invoices found</p>}</div></Panel>; };
const Gateway = ({ instituteId }) => { const q=useQuery({queryKey:['platform','gateway',instituteId],queryFn:()=>platformApi.gateway(instituteId)});if(q.isLoading)return <PageSkeleton/>;if(q.isError)return <ErrorPanel error={q.error} retry={q.refetch}/>;return <Panel><h2 className="font-serif text-xl font-black italic">Payment Gateway</h2><a href={`/platform/gateways?instituteId=${instituteId}`} className="mt-3 inline-block text-sm font-bold text-emerald-700 underline">Manage Payment Gateway</a><div className="mt-6 grid gap-6 sm:grid-cols-2 lg:grid-cols-4"><Field label="Provider" value={q.data.provider}/><Field label="Merchant ID" value={q.data.merchantId}/><Field label="KYC Status" value={q.data.kycStatus}/><Field label="Payments" value={q.data.paymentsEnabled?'Enabled':'Disabled'}/></div></Panel>; };
const Activity = ({ instituteId }) => { const q=useQuery({queryKey:['platform','audit',{instituteId}],queryFn:()=>platformApi.audits({instituteId,page:0,size:25})});if(q.isLoading)return <PageSkeleton/>;if(q.isError)return <ErrorPanel error={q.error} retry={q.refetch}/>;return <Panel><h2 className="font-serif text-xl font-black italic">Activity Timeline</h2><div className="mt-5 space-y-4">{q.data.content.map(x=><div key={x.id} className="border-l-2 border-emerald-200 pl-4"><p className="text-sm font-black">{x.action.replaceAll('_',' ')}</p><p className="mt-1 text-xs text-slate-500">{x.actor} | {formatDate(x.createdAt)} | {x.reason}</p></div>)}</div></Panel>; };
const Notes = ({ instituteId }) => { const client=useQueryClient();const [note,setNote]=useState('');const q=useQuery({queryKey:['platform','notes',instituteId],queryFn:()=>platformApi.notes(instituteId)});const m=useMutation({mutationFn:()=>platformApi.addNote(instituteId,{note}),onSuccess:()=>{setNote('');client.invalidateQueries({queryKey:['platform','notes',instituteId]});}});if(q.isLoading)return <PageSkeleton/>;return <Panel><h2 className="font-serif text-xl font-black italic">Internal Notes</h2><div className="mt-5 flex gap-3"><input value={note} onChange={e=>setNote(e.target.value)} placeholder="Add internal note" className="min-w-0 flex-1 rounded-xl border border-slate-200 px-4"/><button disabled={!note.trim()||m.isPending} onClick={()=>m.mutate()} className="rounded-xl bg-slate-950 px-5 py-3 text-xs font-black uppercase text-white disabled:opacity-40">Add Note</button></div><div className="mt-5 space-y-3">{q.data?.map(x=><div key={x.id} className="rounded-xl bg-slate-50 p-4"><p className="text-sm font-semibold">{x.note}</p><p className="mt-2 text-xs text-slate-400">{x.author} | {formatDate(x.createdAt)}</p></div>)}</div></Panel>; };

export default InstituteDetailsPage;
