import React, { useEffect, useState } from 'react';
import { keepPreviousData, useQuery } from '@tanstack/react-query';
import { Eye, Plus, Search } from 'lucide-react';
import { useNavigate, useSearchParams } from 'react-router-dom';
import { platformApi } from '../../api/platformApi';
import PlatformLayout from '../../components/platform/PlatformLayout';
import { EmptyRow, ErrorPanel, StatusBadge, formatDate } from '../../components/platform/PlatformUi';

const InstitutesPage = () => {
  const plans = useQuery({ queryKey: ['platform', 'plans'], queryFn: platformApi.plans });
  const navigate = useNavigate(); const [params, setParams] = useSearchParams();
  const [search, setSearch] = useState(params.get('search') || '');
  const page = Number(params.get('page') || 0); const status = params.get('status') || ''; const plan = params.get('plan') || '';
  useEffect(() => { const id = setTimeout(() => { const next = new URLSearchParams(params); if (search) next.set('search', search); else next.delete('search'); next.set('page', '0'); setParams(next, { replace: true }); }, 350); return () => clearTimeout(id); }, [search]);
  const filters = { page, size: 25, search: params.get('search') || '', status, plan, paymentGatewayStatus: params.get('gateway') ? 'ACTIVE' : '' };
  const result = useQuery({ queryKey: ['platform', 'institutes', filters], queryFn: () => platformApi.institutes(filters), placeholderData: keepPreviousData });
  const update = (key, value) => { const next = new URLSearchParams(params); value ? next.set(key, value) : next.delete(key); next.set('page', '0'); setParams(next); };
  return <PlatformLayout title="Registered Institutes" subtitle="Server-paginated school and college directory">
    <div className="mb-5 flex justify-end"><button type="button" onClick={() => navigate('/platform/institutes/new')} className="flex items-center gap-2 rounded-xl bg-slate-950 px-5 py-3 text-xs font-black uppercase text-white shadow-lg"><Plus size={16} />Add Institute</button></div>
    <div className="mb-5 grid gap-3 rounded-2xl border border-slate-100 bg-white p-4 shadow-lg shadow-slate-200/20 md:grid-cols-[1fr_180px_180px]"><label className="flex items-center gap-3 rounded-xl border border-slate-200 bg-slate-50 px-4"><Search size={17} className="text-slate-400" /><input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Search institute, code, email, city..." className="h-12 w-full bg-transparent text-sm outline-none" /></label><select value={status} onChange={(e) => update('status', e.target.value)} className="rounded-xl border border-slate-200 bg-white px-4 text-sm font-semibold"><option value="">All statuses</option><option>ACTIVE</option><option>SUSPENDED</option><option>ARCHIVED</option></select><select value={plan} onChange={(e) => update('plan', e.target.value)} className="rounded-xl border border-slate-200 bg-white px-4 text-sm font-semibold"><option value="">All plans</option>{plans.data?.map(p => <option key={p.id} value={p.code}>{p.name}</option>)}</select></div>
    {result.isError ? <ErrorPanel error={result.error} retry={result.refetch} /> : <div className="overflow-hidden rounded-2xl border border-slate-100 bg-white shadow-xl shadow-slate-200/30"><div className="overflow-x-auto"><table className="w-full min-w-[1100px] text-left"><thead className="bg-slate-950 text-[10px] font-black uppercase tracking-widest text-white"><tr>{['Institute', 'Code', 'Type / Location', 'Status', 'Plan', 'Students', 'Teachers', 'Features', 'Registered', 'Expiry', ''].map((h) => <th key={h} className="px-4 py-4">{h}</th>)}</tr></thead><tbody className="divide-y divide-slate-100">{result.data?.content?.length ? result.data.content.map((row) => <tr key={row.id} className="hover:bg-slate-50"><td className="px-4 py-4 font-black text-slate-900">{row.instituteName}</td><td className="px-4 py-4 text-sm font-semibold text-slate-500">{row.institutionCode}</td><td className="px-4 py-4 text-xs font-semibold text-slate-500">{row.type}<br />{row.city}, {row.state}</td><td className="px-4 py-4"><StatusBadge value={row.status} /></td><td className="px-4 py-4"><StatusBadge value={row.plan || 'Unassigned'} /></td><td className="px-4 py-4 font-bold">{row.studentCount}</td><td className="px-4 py-4 font-bold">{row.teacherCount}</td><td className="px-4 py-4 font-bold">{row.enabledFeatureCount}</td><td className="px-4 py-4 text-xs text-slate-500">{formatDate(row.registeredAt)}</td><td className="px-4 py-4 text-xs text-slate-500">{formatDate(row.subscriptionExpiry)}</td><td className="px-4 py-4"><button type="button" title="View institute" onClick={() => navigate(`/platform/institutes/${row.id}`)} className="rounded-lg border border-slate-200 p-2 text-slate-500 hover:text-emerald-700"><Eye size={17} /></button></td></tr>) : <EmptyRow columns={11} text={result.isLoading ? 'Loading institutes...' : 'No institutes found'} />}</tbody></table></div><div className="flex items-center justify-between border-t border-slate-100 px-5 py-4 text-xs font-bold text-slate-500"><span>{result.data ? `${result.data.totalElements} institutes` : ''}</span><div className="flex gap-2"><button disabled={page <= 0} onClick={() => update('page', String(page - 1))} className="rounded-lg border border-slate-200 px-4 py-2 disabled:opacity-40">Previous</button><span className="px-3 py-2">Page {page + 1} of {Math.max(1, result.data?.totalPages || 1)}</span><button disabled={!result.data || page + 1 >= result.data.totalPages} onClick={() => update('page', String(page + 1))} className="rounded-lg border border-slate-200 px-4 py-2 disabled:opacity-40">Next</button></div></div></div>}
  </PlatformLayout>;
};
export default InstitutesPage;
