import React, { useState } from 'react';
import { GraduationCap, LockKeyhole, UserRound } from 'lucide-react';
import { Navigate, useNavigate } from 'react-router-dom';
import { usePlatformAuth } from '../../context/PlatformAuthContext';

const PlatformLogin = () => {
  const { session, login } = usePlatformAuth(); const navigate = useNavigate();
  const [form, setForm] = useState({ username: '', password: '' }); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  if (session?.role === 'SUPER_ADMIN') return <Navigate to="/platform/dashboard" replace />;
  const submit = async (event) => { event.preventDefault(); setBusy(true); setError(''); try { await login(form); navigate('/platform/dashboard'); } catch (e) { setError(e.message); } finally { setBusy(false); } };
  return <div className="flex min-h-screen items-center justify-center bg-[#F8FAFC] px-5 py-12"><div className="w-full max-w-md rounded-4xl border border-slate-100 bg-white p-8 shadow-2xl shadow-slate-200/60 md:p-12"><div className="mx-auto flex h-14 w-14 items-center justify-center rounded-2xl bg-emerald-600 text-white"><GraduationCap size={28} /></div><div className="mt-6 text-center"><p className="text-[10px] font-black uppercase tracking-[0.22em] text-emerald-700">VidyantraErp</p><h1 className="mt-2 font-serif text-3xl font-black italic text-slate-950">Platform Login</h1></div>{error && <div className="mt-6 rounded-xl border border-rose-200 bg-rose-50 px-4 py-3 text-sm font-semibold text-rose-700">{error}</div>}<form onSubmit={submit} className="mt-8 space-y-5"><label className="block"><span className="text-[10px] font-black uppercase tracking-[0.16em] text-slate-600">Username / Email</span><span className="mt-2 flex items-center gap-3 rounded-xl border border-slate-200 bg-slate-50 px-4"><UserRound size={17} className="text-slate-400" /><input required autoComplete="username" value={form.username} onChange={(e) => setForm({ ...form, username: e.target.value })} className="h-12 w-full bg-transparent text-sm outline-none" /></span></label><label className="block"><span className="text-[10px] font-black uppercase tracking-[0.16em] text-slate-600">Password</span><span className="mt-2 flex items-center gap-3 rounded-xl border border-slate-200 bg-slate-50 px-4"><LockKeyhole size={17} className="text-slate-400" /><input required type="password" autoComplete="current-password" value={form.password} onChange={(e) => setForm({ ...form, password: e.target.value })} className="h-12 w-full bg-transparent text-sm outline-none" /></span></label><button disabled={busy} className="w-full rounded-xl bg-slate-950 px-5 py-4 text-xs font-black uppercase tracking-[0.18em] text-white disabled:opacity-50">{busy ? 'Signing In...' : 'Login'}</button></form></div></div>;
};
export default PlatformLogin;
