import React, { useEffect, useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { platformApi } from '../../api/platformApi';
import PlatformLayout from '../../components/platform/PlatformLayout';
import { ErrorPanel, PageSkeleton } from '../../components/platform/PlatformUi';

const PlatformSettingsPage=()=>{const client=useQueryClient();const plans=useQuery({queryKey:['platform','plans'],queryFn:platformApi.plans});const q=useQuery({queryKey:['platform','settings'],queryFn:platformApi.settings});const[form,setForm]=useState({});useEffect(()=>{if(q.data)setForm(Object.fromEntries(q.data.map(x=>[x.key,x.value])))},[q.data]);const m=useMutation({mutationFn:platformApi.updateSettings,onSuccess:()=>client.invalidateQueries({queryKey:['platform','settings']})});if(q.isLoading)return <PlatformLayout title="Platform Settings"><PageSkeleton/></PlatformLayout>;return <PlatformLayout title="Platform Settings" subtitle="Safe product controls without deployment secrets">{q.isError?<ErrorPanel error={q.error} retry={q.refetch}/>:<div className="max-w-3xl rounded-2xl border bg-white p-6 shadow-xl shadow-slate-200/30"><div className="grid gap-5 md:grid-cols-2"><Input label="Default Trial Days" value={form.defaultTrialDays||''} onChange={v=>setForm({...form,defaultTrialDays:v})}/><label className="mt-4 block"><span className="text-[10px] font-black uppercase text-slate-500">Default Plan</span><select value={form.defaultPlan||''} onChange={e=>setForm({...form,defaultPlan:e.target.value})} className="mt-2 h-12 w-full rounded-xl border px-4"><option value="">Select active plan</option>{plans.data?.filter(p=>p.status==='ACTIVE').map(p=><option key={p.id} value={p.code}>{p.name} ({p.code})</option>)}</select>{plans.isError&&<ErrorPanel error={plans.error} retry={plans.refetch}/>}</label><Input label="Support Email" value={form.platformSupportEmail||''} onChange={v=>setForm({...form,platformSupportEmail:v})}/><Input label="Support Phone" value={form.platformSupportPhone||''} onChange={v=>setForm({...form,platformSupportPhone:v})}/><label><span className="text-[10px] font-black uppercase text-slate-500">Registration</span><select value={form.registrationEnabled||'true'} onChange={e=>setForm({...form,registrationEnabled:e.target.value})} className="mt-2 h-12 w-full rounded-xl border px-4"><option value="true">Enabled</option><option value="false">Disabled</option></select></label></div><Input label="Change Reason" value={form.reason||''} onChange={v=>setForm({...form,reason:v})}/>{m.isError&&<p className="mt-4 text-sm font-semibold text-rose-600">{m.error.message}</p>}<button disabled={!form.reason?.trim()||!form.defaultPlan||plans.isLoading||plans.isError||m.isPending} onClick={()=>m.mutate(form)} className="mt-6 rounded-xl bg-slate-950 px-6 py-3 text-xs font-black uppercase text-white disabled:opacity-40">{m.isPending?'Saving...':'Save Settings'}</button></div>}</PlatformLayout>};
const Input=({label,value,onChange})=><label className="mt-4 block"><span className="text-[10px] font-black uppercase text-slate-500">{label}</span><input value={value} onChange={e=>onChange(e.target.value)} className="mt-2 h-12 w-full rounded-xl border px-4 text-sm outline-none focus:border-emerald-500"/></label>;
export default PlatformSettingsPage;
