app.auth.secure-cookies=${APP_AUTH_SECURE_COOKIES:true}
app.auth.same-site=${APP_AUTH_SAME_SITE:None}
app.cors.allowed-origins=${APP_CORS_ALLOWED_ORIGINS:https://erpfrontend-kohl.vercel.app}
app.cors.allowed-origin-patterns=${APP_CORS_ALLOWED_ORIGIN_PATTERNS:}
spring.main.lazy-initialization=${SPRING_MAIN_LAZY_INITIALIZATION:true}
spring.jmx.enabled=${SPRING_JMX_ENABLED:false}
spring.data.jpa.repositories.bootstrap-mode=${SPRING_DATA_JPA_REPOSITORIES_BOOTSTRAP_MODE:lazy}
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:none}
spring.jpa.defer-datasource-initialization=${SPRING_JPA_DEFER_DATASOURCE_INITIALIZATION:false}
app.cashfree.partner-base-url=${CASHFREE_PARTNER_BASE_URL:https://api.cashfree.com/partners}
app.cashfree.payment-base-url=${CASHFREE_PAYMENT_BASE_URL:https://api.cashfree.com/pg}
app.cashfree.environment=${CASHFREE_ENVIRONMENT:production}
app.cashfree.merchant-site-url=${CASHFREE_MERCHANT_SITE_URL:https://erpfrontend-kohl.vercel.app}
