app.auth.secure-cookies=${APP_AUTH_SECURE_COOKIES:true}
app.cors.allowed-origins=${APP_CORS_ALLOWED_ORIGINS:https://erpfrontend-kohl.vercel.app}
app.cors.allowed-origin-patterns=${APP_CORS_ALLOWED_ORIGIN_PATTERNS:}
