app.auth.secure-cookies=${APP_AUTH_SECURE_COOKIES:true}
app.cors.allowed-origins=${APP_CORS_ALLOWED_ORIGINS:https://erpfrontend-kohl.vercel.app}
app.cors.allowed-origin-patterns=${APP_CORS_ALLOWED_ORIGIN_PATTERNS:}
spring.main.lazy-initialization=${SPRING_MAIN_LAZY_INITIALIZATION:true}
spring.jmx.enabled=${SPRING_JMX_ENABLED:false}
spring.data.jpa.repositories.bootstrap-mode=${SPRING_DATA_JPA_REPOSITORIES_BOOTSTRAP_MODE:lazy}
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:none}
spring.jpa.defer-datasource-initialization=${SPRING_JPA_DEFER_DATASOURCE_INITIALIZATION:false}
