import { useState } from 'react';
import { Search, Download, BarChart3 } from 'lucide-react';
import { SectionHeading } from './LandingShared';
import { DashboardPreview } from './HeroSection';

const examples = {
  Students: { title: 'Student Management', description: 'Searchable student profiles and class records.', columns: ['Student', 'Class', 'Status'], rows: [['Sample student 01', 'Class 8 · A', 'Active'], ['Sample student 02', 'Class 9 · B', 'Active'], ['Sample student 03', 'Class 10 · A', 'Active']] },
  Attendance: { title: 'Attendance Management', description: 'Review class attendance for the selected day.', columns: ['Student', 'Class', 'Attendance'], rows: [['Sample student 01', 'Class 8 · A', 'Present'], ['Sample student 02', 'Class 8 · A', 'Present'], ['Sample student 03', 'Class 8 · A', 'Absent']] },
  Fees: { title: 'Fees Management', description: 'Keep fee collections and outstanding dues in view.', columns: ['Student', 'Fee type', 'Status'], rows: [['Sample student 01', 'Tuition', 'Paid'], ['Sample student 02', 'Transport', 'Due'], ['Sample student 03', 'Tuition', 'Paid']] },
  Reports: { title: 'Reports & Insights', description: 'Choose a category and review your institution’s records.', columns: ['Report', 'Category', 'View'], rows: [['Student summary', 'Students', 'Summary'], ['Monthly attendance', 'Attendance', 'Trend'], ['Fee collections', 'Fees', 'Summary']] },
};
export default function ProductPreviewSection() {
  const [screen, setScreen] = useState('Students');
  const sample = examples[screen];
  return <section id="preview" className="landing-section landing-white"><div className="landing-container"><div className="landing-preview-heading"><SectionHeading eyebrow="A CLOSER LOOK AT YOUR DAY-TO-DAY" title="See VidyantraErp in action">Explore the types of workflows available in your institution’s workspace.</SectionHeading><span className="landing-small-note">Illustrative previews · Sample data only</span></div><div className="landing-preview-switcher" role="group" aria-label="Choose product preview">{['Dashboard', ...Object.keys(examples)].map(name => <button type="button" key={name} aria-pressed={screen === name} aria-controls="product-preview-panel" onClick={() => setScreen(name)}>{name}</button>)}</div><div id="product-preview-panel" className="landing-product-panel" aria-live="polite">{screen === 'Dashboard' ? <DashboardPreview /> : <div className="landing-table-preview"><div className="table-preview-heading"><div><h3>{sample.title}</h3><p>{sample.description}</p></div><span className="landing-icon"><BarChart3 size={22} /></span></div><div className="preview-search"><Search size={16} aria-hidden="true" /><span>{screen === 'Reports' ? 'Filter reports by category' : `Search ${screen.toLowerCase()}`}</span><span className="preview-export"><Download size={14} /> Export</span></div><table><caption className="sr-only">{sample.title} with illustrative sample records</caption><thead><tr>{sample.columns.map(column => <th key={column} scope="col">{column}</th>)}</tr></thead><tbody>{sample.rows.map(row => <tr key={row[0]}>{row.map((value, i) => <td key={i}>{i === 2 ? <span className={`preview-record-status ${['Absent', 'Due'].includes(value) ? 'pending' : ''}`}>{value}</span> : value}</td>)}</tr>)}</tbody></table><p className="landing-small-note">Preview only. The working ERP uses your institution’s authorized records.</p></div>}</div></div></section>;
}
