import { Building2, ShieldCheck, Cloud, SlidersHorizontal, BarChart3, Check, ArrowRight, Users, GraduationCap, BookOpen, LockKeyhole, Fingerprint, ScrollText, Search, Layers, Gauge, QrCode } from 'lucide-react';
import { SectionHeading } from './LandingShared';

export function TrustStrip() {
  return <div className="landing-trust"><div className="landing-container">{[[Building2, 'Multi-school ready', 'One platform, distinct institutions'], [ShieldCheck, 'Role-based access', 'Permissions for each responsibility'], [SlidersHorizontal, 'Modular features', 'Access matched to your plan'], [Cloud, 'Cloud-based', 'Your workspace in a browser'], [BarChart3, 'Connected reporting', 'A clearer view across departments']].map(([Icon, title, description]) => <div key={title}><Icon size={22} aria-hidden="true" /><strong>{title}</strong><span>{description}</span></div>)}</div></div>;
}

export function ProblemSolutionSection() {
  return <section id="about" className="landing-section"><div className="landing-container landing-two-column"><SectionHeading eyebrow="LESS ADMIN. MORE CLARITY." title="Manage your entire institution from one platform">VidyantraErp is a cloud-based School &amp; College ERP that connects academic, administrative and campus operations. Replace scattered records with a shared, searchable source of information.</SectionHeading><div className="landing-workflow-table"><div className="workflow-table-head"><span>The everyday challenge</span><span>With VidyantraErp</span></div>{[['Separate spreadsheets', 'Centralized institution records'], ['Repeated data entry', 'Connected modules and workflows'], ['Manual attendance registers', 'Class-wise digital attendance'], ['Unclear fee dues', 'Collections and payment history'], ['Delayed departmental reports', 'Reports from saved ERP records'], ['Disconnected teams', 'Role-based access to shared work']].map(([before, after]) => <div className="workflow-table-row" key={before}><span>{before}</span><span><Check size={15} aria-hidden="true" />{after}</span></div>)}</div></div></section>;
}

export function HowItWorksSection() {
  return <section className="landing-section"><div className="landing-container"><SectionHeading eyebrow="A CLEAR PATH TO YOUR NEW WORKSPACE" title="Get started in three simple steps" /><ol className="landing-steps">{[['Register your institute', 'Create your institution profile and verify your email to begin.'], ['Set up your plan and modules', 'Start with the configured trial. Discuss the right plan and modules as you grow.'], ['Bring your institution together', 'Add students and teachers, set up classes, and start using your enabled modules.']].map(([title, text], i) => <li key={title}><span className="step-number">0{i + 1}</span><h3>{title}</h3><p>{text}</p></li>)}</ol><div className="landing-step-footer"><span>Register <ArrowRight size={14} /> Set up institute <ArrowRight size={14} /> Add your people <ArrowRight size={14} /> Start managing</span></div></div></section>;
}

export function RoleSection() {
  return <section id="solutions" className="landing-section landing-white"><div className="landing-container"><SectionHeading eyebrow="EVERY ROLE, IN THE RIGHT PLACE" title="One platform. A workspace for everyone.">Focused access helps your team get on with their work.</SectionHeading><div className="landing-three-column">{[[ShieldCheck, 'Admin', 'Coordinate institute operations, fees, staff, reports and settings.', 'blue'], [GraduationCap, 'Teacher', 'Work with attendance, timetables, marks and assigned academic responsibilities.', 'emerald'], [BookOpen, 'Student', 'View your own profile, fees, timetable, examinations and permitted campus services.', 'amber']].map(([Icon, title, text, color]) => <article className="landing-role-card" key={title}><span className={`landing-icon ${color}`}><Icon aria-hidden="true" /></span><h3>{title}</h3><p>{text}</p><span className="landing-small-note">Access depends on role and enabled features.</span></article>)}</div><div className="landing-solutions"><article><p className="landing-eyebrow">FOR SCHOOLS</p><h3>Keep the school day connected.</h3><p>Admissions, attendance, fees, timetables, results, transport and library — organized around students and staff.</p></article><article><p className="landing-eyebrow">FOR COLLEGES</p><h3>Bring campus operations together.</h3><p>Coordinate student and faculty records, classes and subjects, examinations, fees and institutional reporting.</p></article></div></div></section>;
}

export function MultiTenantSection() {
  return <section className="landing-section"><div className="landing-container landing-two-column"><div><SectionHeading eyebrow="GROW WITHOUT MIXING YOUR RECORDS" title="Built for multiple institutions">Each school or college has its own users, data, settings, subscription and enabled modules. Institution-level separation keeps everyday work scoped to the right campus.</SectionHeading><p className="landing-body-copy">Platform-level institute management brings subscription and feature administration together while keeping institution workspaces separate.</p></div><div className="landing-tenant-map"><div className="tenant-root"><Building2 size={24} aria-hidden="true" /><strong>VidyantraErp</strong><span>One platform</span></div><div className="tenant-branches">{['School A', 'School B', 'College C', 'School D'].map(name => <div key={name}><Building2 size={20} aria-hidden="true" /><strong>{name}</strong><span>Own users · Own records</span><span>Own plan · Own modules</span></div>)}</div><p className="landing-small-note">Illustrative institutions, not customer endorsements.</p></div></div></section>;
}

export function SecuritySection() {
  const items = [[ShieldCheck, 'Role-based access', 'Permissions scope what administrators, teachers and students can do.'], [Building2, 'Institution-level separation', 'Tenant-scoped access keeps records within the appropriate institution.'], [Fingerprint, 'Protected sign-in', 'JWT authentication and hashed passwords support account protection.'], [LockKeyhole, 'Session controls', 'Refresh-session handling and password-change controls protect access.'], [ScrollText, 'Platform audit records', 'Administrative subscription and configuration changes are logged.'], [Users, 'Protected administration', 'Platform identities and tenant business access have separate boundaries.']];
  return <section id="security" className="landing-section landing-security"><div className="landing-container"><SectionHeading eyebrow="TRUST STARTS WITH RESPONSIBLE DESIGN" title="Secure by design">Practical access controls help protect the information your institution relies on.</SectionHeading><div className="landing-three-column">{items.map(([Icon, title, text]) => <article key={title}><Icon size={23} aria-hidden="true" /><h3>{title}</h3><p>{text}</p></article>)}</div></div></section>;
}

export function PerformanceSection() {
  return <section className="landing-section landing-white"><div className="landing-container"><SectionHeading eyebrow="READY FOR THE NEXT ACADEMIC YEAR" title="Designed for growing institutions">Find records, load relevant information, and keep day-to-day work moving as your institution grows.</SectionHeading><div className="landing-three-column">{[[Search, 'Find what matters', 'Search, filters and server-side pagination help you work through larger student and report directories.'], [Layers, 'Load what you need', 'On-demand module loading and cached queries reduce repeated work in the browser.'], [Gauge, 'Purposeful data handling', 'Lightweight responses and aggregate report queries support everyday academic and financial workflows.']].map(([Icon, title, text]) => <article className="landing-feature-panel" key={title}><Icon size={23} aria-hidden="true" /><h3>{title}</h3><p>{text}</p></article>)}</div></div></section>;
}

export function ReportingSection() {
  return <section className="landing-section"><div className="landing-container landing-two-column"><div><SectionHeading eyebrow="FROM RECORDS TO DECISIONS" title="Better decisions with clear reports">Review students, attendance, fees, examinations and results, teachers, salary, timetable, library, transport, hostel and holidays — where enabled for your institution.</SectionHeading><a className="landing-text-link" href="#preview">See the product preview <ArrowRight size={15} /></a></div><div className="landing-feature-panel qr-panel"><QrCode size={37} aria-hidden="true" /><h3>QR-based student &amp; teacher identification</h3><p>Identify students or teachers quickly within permitted ERP workflows. Access checks still apply to the information a user can see.</p><span className="landing-small-note">Available within the ERP scanner workflow.</span></div></div></section>;
}

export function WhySection() {
  return <section className="landing-section landing-white"><div className="landing-container"><SectionHeading eyebrow="A MORE CONNECTED WAY TO WORK" title="Why choose VidyantraErp?" /><div className="landing-reasons">{[['All-in-one ERP', 'Academics, finance and operations in one workspace.'], ['Multi-institute ready', 'An individual workspace for every institution.'], ['Modular features', 'The right tools for the way your team works.'], ['Secure access', 'Role and institute boundaries built into access.'], ['Organized data', 'Searchable records and practical reporting.'], ['Flexible subscriptions', 'Platform-managed plans for different needs.']].map(([title, text]) => <div key={title}><Check size={18} aria-hidden="true" /><div><h3>{title}</h3><p>{text}</p></div></div>)}</div></div></section>;
}

export function FinalCTA() {
  return <section className="landing-final"><div className="landing-container"><div><p className="landing-eyebrow">MAKE ROOM FOR WHAT MATTERS</p><h2>Ready to simplify your institution management?</h2><p>Bring students, staff, fees, attendance, exams, transport and reporting into one platform.</p></div><div className="landing-cta-row"><a href="#contact" className="landing-button secondary">Request Demo <ArrowRight size={17} /></a></div></div></section>;
}
