import LegalPage from './LegalPage';
const sections = [
  ['Account information', 'Registration and account management use details such as institution name, email, contact information, profile details and role assignments. Email verification and authentication records support sign-in and account recovery.'],
  ['Institution, student and staff records', 'Institutions use enabled modules to store and manage academic, administrative and operational records. These may include student and teacher profiles, attendance, fees, examinations, salary and campus services. Institutions are responsible for entering appropriate information and managing user permissions.'],
  ['Demo and support enquiries', 'The demo form collects your name, institution, email, phone, institution type, approximate student count and any optional city or message. These details are stored for follow-up and may be sent as a plain-text notification to the configured platform support mailbox. Please do not send student records or passwords through this form.'],
  ['Cookies and browser storage', 'Authentication uses essential session mechanisms, including refresh cookies and limited browser-stored account information. Email-verification state may also be kept in the browser. The public landing page does not add advertising trackers or non-essential analytics.'],
  ['Service providers', 'Running the service involves infrastructure providers for hosting and databases, and configured providers for email, file storage or payments where those features are used. Information needed for a requested workflow may pass to its configured provider. Ask support for the providers used for your institution’s deployment.'],
  ['Access and security', 'The service uses institute-scoped access, role permissions, password hashing and authenticated sessions. Platform administration has separate access controls. Institutions should assign permissions carefully and users should protect their credentials.'],
  ['Retention and deletion', 'Records may remain stored while they are needed for service delivery, support, account administration or institution requirements. Retention periods and deletion arrangements should be confirmed with your institution and platform support. A fixed automatic deletion period is not specified here.'],
  ['Information requests and corrections', 'Contact your institution for changes to academic, student or staff records. Contact platform support for enquiries about a demo submission or a platform-managed account. Support may need to verify your authority before acting on a request.'],
];
export default function PrivacyPage() { return <LegalPage title="Privacy Policy" introduction="This page explains the information used by VidyantraErp and the purpose it serves when institutions and their users work with the platform." sections={sections} />; }
