import LegalPage from './LegalPage';
const sections = [
  ['Permitted use', 'Use VidyantraErp for authorized school or college administration and related academic workflows. Do not attempt to access another institution’s records, bypass access controls, interfere with the service, or submit malicious content.'],
  ['Account responsibility', 'Institutions are responsible for choosing authorized administrators, maintaining accurate registration details and assigning appropriate permissions. Users are responsible for protecting their credentials and reporting suspected account misuse.'],
  ['Subscriptions and trials', 'Enabled modules, capacity limits, billing periods and trial availability depend on platform configuration and your institution’s subscription. A trial begins on the configured default plan. Paid plan assignment, upgrades and other changes are handled through platform subscription management. Confirm pricing, taxes, payment, cancellation and renewal arrangements with support before purchasing.'],
  ['Service availability', 'Access can be affected by maintenance, network conditions, infrastructure issues or subscription status. Availability and capacity commitments, if any, must be confirmed in your institution’s service agreement. The public website does not promise uninterrupted service or unlimited scale.'],
  ['Institution data responsibilities', 'Your institution is responsible for the accuracy of records it enters, the authority to process them and the permissions it grants. Only submit information needed for legitimate institution workflows. Keep any copies or exports your institution requires for its own recordkeeping.'],
  ['Suspension and access restrictions', 'Access may be restricted by institution status, subscription expiry, disabled features or security controls. Contact support to understand the reason for a restriction and the steps needed to restore permitted access.'],
  ['Termination and data arrangements', 'Contact platform support to discuss ending service, account closure and any required export or deletion arrangements. Confirm these arrangements before closing an institution’s account. No automatic deletion or refund commitment is made by this page.'],
  ['Intellectual property', 'Use of the service does not transfer ownership of VidyantraErp software or branding. Institution-supplied records and materials remain subject to their owners’ rights. Do not upload material you are not authorized to use.'],
];
export default function TermsPage() { return <LegalPage title="Terms of Service" introduction="These service terms describe the expected use of VidyantraErp. Institution-specific commercial arrangements should be confirmed with platform support before subscribing." sections={sections} />; }
